image: docker:latest

variables:
  REPOSITORY_URL: 043607157156.dkr.ecr.eu-west-1.amazonaws.com/foodcheri/buildenv

services:
- docker:dind

before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli

stages:
  - build

build:
  stage: build
  script:
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - docker build -t $REPOSITORY_URL .
    - docker push $REPOSITORY_URL
  only:
    - master
