steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "eu.gcr.io/foodcheri-gae/symfony-buildenv:latest", "."]

- name: "gcr.io/cloud-builders/docker"
  args: ["push", "eu.gcr.io/foodcheri-gae/symfony-buildenv:latest"]

timeout: "1600s"
